title: stlaGblog
tagline: a blog about Mathematics, R, Statistics, ...
logo: assets/img/07-10-06_2241.jpg 

# Choose url: / for local development
url: http://stla.github.com/Test_Poirot3/
rawurl: https://raw.github.com/stla/Test_Poirot3/gh-pages/
# url: /
URL: http://github.com/ramnathv/poirot
navigation: 
  - {item: Home, href: index.html}
  - {item: About, href: about.html}
  
# WIDGETS
disqus:
  shortname: whereistheshortname
