mode     : selfcontained
framework: purus
github:
  user: stla
  repo: Test_Poirot3

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

url:
  lib: ../libraries
  assets: ../assets

# WIDGETS
widgets: [disqus,mathjax]





