mode     : selfcontained
framework: purus
github:
  user: ramnathv
  repo: poirot

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

url:
  lib: ../libraries
  assets: ../assets

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify



